spring.application.name=finance_tracker

spring.datasource.url=jdbc:postgresql://localhost:5434/postgres
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret-key=6ce2758effe2a63cd1e37141bef18955c7f8fc5919341e6b23ae99f825da8d61
security.jwt.expiration-time=9000000000000000